#!/usr/bin/env bash
# 호스트에서 Raspberry Pi 4용 Yocto 이미지와 QEMU 테스트 커널을 빌드한다.

set -euo pipefail
source "$(cd "$(dirname "$0")" && pwd)/scripts/common.sh"

[[ $EUID -ne 0 ]] || die "BitBake는 root로 실행하지 마십시오."
[[ -f "$POKY_DIR/oe-init-build-env" ]] || die "먼저 ./setup-yocto.sh를 실행하십시오."
[[ -d "$RPI_LAYER_DIR/conf" ]] || die "meta-raspberrypi 레이어가 없습니다."

export LANG="${LANG:-C.UTF-8}"
export LC_ALL="${LC_ALL:-C.UTF-8}"

# oe-init-build-env는 작업 디렉터리를 변경하므로 절대경로를 사용한다.
set +u
source "$POKY_DIR/oe-init-build-env" "$BUILD_DIR"
set -u

bitbake-layers add-layer "$RPI_LAYER_DIR" 2>/dev/null || true
bitbake-layers add-layer "$CUSTOM_LAYER_DIR" 2>/dev/null || true

cat > conf/auto.conf <<EOF
# Generated by build-image.sh. Local developer settings belong in local.conf.
MACHINE = "raspberrypi4-64"
BB_NUMBER_THREADS = "${BB_NUMBER_THREADS:-$(nproc)}"
PARALLEL_MAKE = "-j ${PARALLEL_MAKE_JOBS:-$(nproc)}"
DL_DIR = "$PROJECT_ROOT/downloads"
SSTATE_DIR = "$PROJECT_ROOT/sstate-cache"

# Keep an uncompressed image for QEMU and a compressed image for distribution.
IMAGE_FSTYPES = "wic wic.bz2"

# PoC login automation. Remove debug-tweaks for production images.
EXTRA_IMAGE_FEATURES += "debug-tweaks"
SERIAL_CONSOLES = "115200;ttyAMA0"
EOF

echo "===== Yocto build configuration ====="
bitbake-layers show-layers
echo "===== Building core-image-base ====="
bitbake core-image-base

echo "===== Build artifacts ====="
find "$DEPLOY_DIR" -maxdepth 1 \
    \( -name 'Image*' -o -name 'bcm2711-rpi-4-b.dtb' -o -name '*.wic' -o -name '*.wic.bz2' \) \
    -printf '%f\n' | sort
