#!/bin/bash
# Build the Wrynose Raspberry Pi 4 image inside the crops container.
set -euo pipefail

exec > >(tee -a /workdir/build.log) 2>&1
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

echo "===== WRYNOSE BUILD START ($(date)) ====="
cd /workdir

set +u
source sources/oe-core/oe-init-build-env build
set -u

bitbake-layers add-layer ../sources/meta-raspberrypi 2>/dev/null || true
bitbake-layers add-layer ../meta-device-simulation 2>/dev/null || true

cat > conf/auto.conf <<EOF
# Generated by run-build.sh. Developer-local settings belong in local.conf.
MACHINE = "raspberrypi4-64"
BB_NUMBER_THREADS = "${BB_NUMBER_THREADS:-16}"
PARALLEL_MAKE = "-j ${PARALLEL_MAKE_JOBS:-16}"
DL_DIR = "/workdir/downloads"
SSTATE_DIR = "/workdir/sstate-cache"
BB_HASHSERVE_DB_DIR = "/workdir/sstate-cache"

ENABLE_UART = "1"
SERIAL_CONSOLES = "115200;ttyAMA0"
EXTRA_IMAGE_FEATURES += "allow-empty-password empty-root-password allow-root-login serial-autologin-root"
IMAGE_FSTYPES = "wic wic.bz2"
LICENSE_FLAGS_ACCEPTED += "synaptics-killswitch"
EOF

echo "===== Active layers ====="
bitbake-layers show-layers
echo "===== Building core-image-base ====="
bitbake core-image-base

echo "===== Build artifacts ====="
find tmp/deploy/images/raspberrypi4-64 -maxdepth 1 \
    \( -name 'Image*' -o -name 'bcm2711-rpi-4-b.dtb' \
       -o -name '*.wic' -o -name '*.wic.bz2' \) \
    -printf '%f\n' | sort
